language: ruby
cache: bundler
bundler_args: --without system_tests
script: "bundle exec rake validate lint"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.5
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.2
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
